### ISSUE TITLE
Refresh Tokens for AWS Sessions

### ISSUE THREAD

**Issue by six0h** [vancluever/aws-runas#10]
They're not implemented, do I have to submit a pull request or something to get things done around here?! ;)

**Comment by vancluever** [comment]
Haha, hey @six0h :wink:

You are more than welcome to! Definitely don't know when I am going to have the time to look at it 100%, but it is something that I have floated around a bit. The main issue is right now (if I'm understanding it properly), is that since `aws-runas` just launches whatever it need to launch (external command or shell) as a fork/exec process with appropriately set env variables, there's no easy way to refresh that environment in place. Hence it's always just been a lot less complex for me to just end my current session and re-run it from history.

If you can figure out a good way to get it in though, I think it would be a pretty cool addition :) I'm guessing if we are talking about the interactive shells, we would need a way for `aws-runas` to basically "supervise" the shell and then re-launch it when the token expired (and also make sure that it wasn't killing anything that was running at the time).

Let me know your thoughts/code! :grinning:

**Comment by six0h** [comment]
Hey! :) I thought that would give you a chuckle. Yeah, I can't recall the refresh token functionality exactly for AWS, but I was thinking there is likely a way to refresh the token everytime the command is run. I can deal with going away for an hour and coming back and having to build a new session, but while I'm actively working for more than an hour, the token should refresh each time things are run.

Again, I can't remember the exact functionality of AWS Refresh tokens, so maybe this is not a viable approach. When I have a few minutes to check again, i'll do so.

**Comment by vancluever** [comment]
Sounds good :+1: we could just always increase the timeout as well, but of course that would mean all sessions (even non-interactive sessions) get the same expiry. 

It's hardcoded here: https://github.com/vancluever/aws-runas/blob/master/lib/aws_runas/main.rb#L56

**Comment by six0h** [comment]
hey, thanks for linking i just saw this message so i'll take another look in a minute.

I looked through the code yesterday, i see you're basically just popping open another shell with some env vars set. that makes things a little more complicated as we're not actively doing anything, there's just a regular shell open with some custom settings.

i shall put some more thought into this now that i've seen how it works :) thanks for your work, this is a good tool!
