### ISSUE TITLE
Feature request: running against a generic ARN

### ISSUE THREAD

**Issue by et304383** [vancluever/aws-runas#19]
Would be nice if I could do something like:

aws-runas --arn=<arn for a role>

and have it rely on EC2 credentials

**Comment by vancluever** [comment]
Hey @et304383, I've given this some thought (not just this weekend but on and off since the issue has been submitted) and while I think that this would be a neat feature, with the current codebase the way it is, it would be a little too complex to implement in code for it to be worthwhile.

Consider that the main driver to the selection of credentials and details is the AWS CLI configuration profiles - this determines the role ARN to use, the MFA ARN to use if it is needed (which is determined by looking at config), and the source credentials profile to use. Overriding the role ARN has the potential to make for an awkward UX as while the role ARN would be overridden, we are implying that none of the other settings are, which may or may not be the case. This then opens up the question of whether or not we should support all of the others for manual selection too.

All of this has implications through most of the workflow (including `AwsRunAs::Cli`, `AwsRunAs::Main`, and `AwsRunAs::Config`, possibly more too). That then cascades down to tests, and all in all is more change that I'm personally comfortable with here right now.

Hopefully this is not too much of an inconvenience for you!
